//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.25 at 12:51:41 PM IST 
//


package com.ert.schemas.phonebook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "phoneBook"
})
@XmlRootElement(name = "PhoneBooks")
public class PhoneBooks {

    @XmlElement(name = "PhoneBook", required = true)
    protected List<PhoneBook> phoneBook;

    public List<PhoneBook> getPhoneBook() {
        if (phoneBook == null) {
            phoneBook = new ArrayList<PhoneBook>();
        }
        return this.phoneBook;
    }

}
